name: Deploy

on:
  push:
    branches:
      - master
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          if ! command -v docker compose &> /dev/null; then
            curl -SL https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose
            chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
          fi

      - name: Set environment variables
        run: |
          if [[ ${{ startsWith(github.ref, 'refs/tags/v') }} ]]; then
            echo "IMAGE_TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
            echo "VITE_ENVIRONMENT=" >> $GITHUB_ENV
            echo "VITE_API_URL=api.rutineret.c.th.fitfit.dk" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
            echo "VITE_ENVIRONMENT=dev." >> $GITHUB_ENV
            echo "VITE_API_URL=dev.api.rutineret.c.th.fitfit.dk" >> $GITHUB_ENV
          fi

      - name: Build and push with Docker Compose
        env:
          VITE_API_URL: ${{ env.VITE_API_URL }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          docker compose build
          docker compose push

      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          chmod +x skaffold-linux-amd64
          sudo mv skaffold-linux-amd64 /usr/local/bin/skaffold

      - name: Run Skaffold
        env:
          VITE_ENVIRONMENT: ${{ env.VITE_ENVIRONMENT }}
          VITE_API_URL: ${{ env.VITE_API_URL }}
        run: skaffold run
