name: Deploy

on:
  push:
    branches:
      - master
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: |
          if ! command -v docker compose &> /dev/null; then
            curl -SL https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose
            chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
          fi

      - name: Install helm/helmfile/sops
        uses: alexellis/arkade-get@master
        with:
          helm: v3.12.3
          helmfile: v1.2.3
          sops: v3.7.3

      - name: Set environment variables for tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "IMAGE_TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          echo "VITE_ENVIRONMENT=prod" >> $GITHUB_ENV
          echo "DOMAIN=rutineret.c.th.fitfit.dk" >> $GITHUB_ENV
          echo "VITE_API_URL=api.rutineret.c.th.fitfit.dk" >> $GITHUB_ENV

      - name: Set environment variables for master
        if: github.ref == 'refs/heads/master'
        run: |
          echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          echo "VITE_ENVIRONMENT=dev" >> $GITHUB_ENV
          echo "DOMAIN=dev.rutineret.c.th.fitfit.dk" >> $GITHUB_ENV
          echo "VITE_API_URL=dev.api.rutineret.c.th.fitfit.dk" >> $GITHUB_ENV

      - name: Echo environment variables
        run: env

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push with Docker Compose
        run: |
          docker compose build
          docker compose push

      - name: Configure kubectl
        run: |
          mkdir $PWD/.kube
          echo "${{ secrets.KUBECONFIG }}" > $PWD/.kube/config
          echo "KUBECONFIG=$PWD/.kube/config" >> $GITHUB_ENV

      - name: Get nodes
        run: kubectl get nodes

      - name: Setup Skaffold
        run: |
          wget https://storage.googleapis.com/skaffold/releases/${VERSION}/${BINARY} -O ./skaffold
          chmod +x ./skaffold
        env:
          VERSION: v2.6.0
          BINARY: skaffold-linux-amd64

      - name: Run Skaffold
        run: ./skaffold deploy --images tons/rutineret-web:$IMAGE_TAG
